[theme]
# PRECISION LIGHT - Grey, Orange & Marine
# base = "light" erzwingt immer das helle Theme,
# unabh√§ngig vom OS- oder Browser-Darkmode
base = "light"
primaryColor = "#1B3A6B"             # Deep Marine
backgroundColor = "#868686" #"#F8F9FA"          # Sanftes Hellgrau/Off-White
secondaryBackgroundColor = "#FFFFFF"  # Karten/Inputs
textColor = "#1E293B"                # Dunkles Schieferblau
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
